/*CRIANDO TABELA*/
CREATE TABLE IF NOT EXISTS PRODUCT (

    id_produto INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    PRODUCT_PRICE FLOAT,
    PRODUCT_DESCRIPTION VARCHAR(150)
    );

-- CADASTRO DE PRODUTOS

INSERT INTO PRDUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DESCRIPTION)
VALUES
    ('Spaten', 4.25, 'Lata - 350 ml'),
    ('Coronitta', 5, 'Garrafa - 210 ml'),
    ('Ama', 3 , 'Lata - 350 ml');

UPDATE PRODUCT
SET PRODUCT_NAME=' Coronita'
WHERE PRODUCT_NAME='Coronita';

UPDATE PRODUCT
SET PRODUCT_NAME='Ama'
WHERE PRODUCT_NAME='Agua - AMA';

ALTER TABLE PRODUCT
    ADD COLUMN ORIGIN VARCHAR;

INSERT INTO PRODUCT (PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_DESCRIPTION, ORIGIN)
VALUES
    ('Skol beats', 6.05 , 'Lata - 269 ml', 'Nacional');

CREATE TABLE if NOT EXISTS TYPE_PRODUCT (
        id INT AUTO_INCREMENT PRIMARY KEY,
        TYPE_NAME_PRODUCT VARCHAR(50),
        CATEGORY VARCHAR (30)
    );

ALTER TABLE PRODUCT ADD TYPE_PRODUCT_ID INT;
ALTER TABLE PRODUCT ADD CONSTRAINT FK_TYPE_PRODUCT FOREIGN KEY (TYPE_PRODUCT_ID) REFERENCES TYPE_PRODUCT(id);


INSERT INTO TYPE_PRODUCT (TYPE_NAME_PRODUCT, CATEGORY)
VALUES
    ('Agua', 'Não-alcoólico'),
    ('Suco', 'Não-alcoólico'),
    ('Cerveja', 'Alcoólico'),
    ('Vinho', 'Não-alcoólico');

UPDATE PRODUCT
SET TYPE_PRODUCT_ID='1'
WHERE ID_PRODUCT=1;

UPDATE PRODUCT
SET TYPE_PRODUCT_ID='2'
WHERE ID_PRODUCT=2;

UPDATE PRODUCT
SET TYPE_PRODUCT_ID='3'
WHERE ID_PRODUCT=3;

UPDATE PRODUCT
SET tipo_produto_id='4'
WHERE ID_PRODUCT=4;

SELECT * FROM PRODUCT;
SELECT * FROM TYPE_PRODUCT;

SELECT PRODUCT.NAME_PRODUCT, TYPE_PRODUCT.TYPE_NAME_PRODUCT, TYPE_PRODUCT.CATEGORY, TYPE_PRODUCT.PRODUCT_DESCRIPTION, TYPE_PRODUCT.PRODUCT_PRICE FROM PRODUCT
         INNER JOIN TYPE_PRODUCT ON PRODUCT.TYPE_PRODUCT_ID = TYPE_PRODUCT.ID;